all:
  children:
    grafana:
      hosts:
        grafana-01:
          ansible_host: 10.0.1.10
    prometheus:
      hosts:
        prometheus-01:
          ansible_host: 10.0.1.20
    node_exporter:
      hosts:
        app-server-01:
          ansible_host: 10.0.2.10
        app-server-02:
          ansible_host: 10.0.2.11
    cloudwatch:
      hosts:
        app-server-01:
        app-server-02:
